version: '3.3'
services:

  db:
    container_name: 'foodgram_db'
    image: postgres:16

    ports:
      - '6432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - foodgram-network
    volumes:
      - pg-booking-data:/var/lib/postgresql/data
    env_file:
      - ../backend/.env

  backend:
    container_name: 'foodgram_backend'
    build:
      context: ../backend/
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - foodgram-network
    env_file:
      - ../backend/.env

  frontend:
    container_name: 'foodgram_frontend'
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: 'foodgram_nginx'
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

volumes:
  pg-booking-data:
networks:
  foodgram-network: