version: '3.3'
services:
  db:
    container_name: 'tests'
    image: postgres:16
    environment:
      POSTGRES_DB: tests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pg-tests-data:/var/lib/postgresql/data

volumes:
  pg-tests-data:
#