version: '3.3'
services:
  db:
    container_name: 'tests'
    image: postgres:16
    ports:
      - '7432:5432'
    volumes:
      - pg-tests-data:/var/lib/postgresql/data

volumes:
  pg-tests-data:
#