version: '3.3'
services:
  db:
    container_name: 'tests'
    image: postgres:16
    ports:
      - '5432:5432'
    volumes:
      - pg-tests-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg-tests-data:
#