"""subscription model added

Revision ID: 02
Revises: 01
Create Date: 2024-10-30 16:32:12.709128

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02"
down_revision: Union[str, None] = "01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usersubscription",
        sa.Column("autor", sa.Integer(), nullable=False),
        sa.Column("subscriber", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["autor"], ["user.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["subscriber"], ["user.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usersubscription")
    # ### end Alembic commands ###
