"""unique constraint added to SubscriptionModel

Revision ID: 04
Revises: 03
Create Date: 2024-10-30 23:59:52.644543

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "04"
down_revision: Union[str, None] = "03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "author cannot be subscriber",
        "subscription",
        ["author_id", "subscriber_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "author cannot be subscriber", "subscription", type_="unique"
    )
    # ### end Alembic commands ###
