"""recipeimage model changed

Revision ID: 12
Revises: 11
Create Date: 2024-11-07 11:17:32.668919

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12"
down_revision: Union[str, None] = "11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe", sa.Column("image", sa.Integer(), nullable=False))
    op.drop_constraint("recipe_image_id_fkey", "recipe", type_="foreignkey")
    op.create_foreign_key(None, "recipe", "recipeimage", ["image"], ["id"])
    op.drop_column("recipe", "image_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipe",
        sa.Column(
            "image_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "recipe", type_="foreignkey")
    op.create_foreign_key(
        "recipe_image_id_fkey", "recipe", "recipeimage", ["image_id"], ["id"]
    )
    op.drop_column("recipe", "image")
    # ### end Alembic commands ###
