MAIN_HOST = "0.0.0.0"
BACKEND_PORT = 8000
MAIN_URL = f"http://{MAIN_HOST}:{BACKEND_PORT}"
PAGINATION_LIMIT = 3
PARAMS_MAX_LENGTH = 200
USER_PARAMS_MAX_LENGTH = 150
MOUNT_PATH = "/media/recipes/images"
MAX_EMAIL_LENGTH = 254
