name: CI

on:
  push:
    branches: [ main ]
    pull_request: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          cd backend
          pip install poetry
          poetry install

      - name: Ruff linter check
        run: | 
          ruff check
