name: CI

on:
  push:
    branches: [ main ]
    pull_request: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          cd backend
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install wkhtmltopdf

      - name: Ruff linter check
        run: |
          ruff check
          ruff format

      - name: Run tests
        env:
          MODE: ${{ secrets.MODE }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_USER_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          ALGORITHM: ${{ secrets.ALGORITHM }}

        run: |
          cd infra
          touch .env
          echo POSTGRES_DB=${{ secrets.DB_NAME }} >> .env
          echo POSTGRES_USER=${{ secrets.DB_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.DB_USER_PASSWORD }} >> .env          
          docker compose -f docker-compose-tests.yml up -d --build
          cd ../backend
          pytest

  build_and_push_to_docker_hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      needs: tests
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to Docker
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Push to Docker Hub
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/foodgram-backend-fastapi:latest
