name: CI

on:
  push:
    branches: [ main ]
    pull_request: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0
      - name: Install dependencies
        run: |
          cd backend
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Ruff linter check
        run: |
          ruff check
          ruff format
      - name: running tests
        run: |
          cd backend
          pytest
